### ISSUE TITLE
Training Lora

### ISSUE THREAD

**Issue by Pascapone** [bupticybee/FastLoRAChat#1]
Serving the model works fine. As soon as i try to train the model, i get an error right after the wandb logging options:
module 'fastchat.conversation' has no attribute 'default_conversation'

**Comment by bupticybee** [comment]
It's because the fastchat version has been updated, try using 4732169b937acc1b0ecb3f88656f9097f33ae841 commit, that will solve the problem.

```
gith clone https://github.com/lm-sys/FastChat.git
cd FastChat
git checkout 4732169b937acc1b0ecb3f88656f9097f33ae841
pip install -e .
```

**Comment by bupticybee** [comment]
Closing because this issue is not active for too long, reopen if necessary.
